### ISSUE TITLE
mapping somehow takes up too much system memory

### ISSUE THREAD

**Issue by yo217** [dataanalysis3/datan3_2019#10]
![IMG_6726639C3E0C-1](https://user-images.githubusercontent.com/46598475/54095729-a09d4300-43a0-11e9-82bb-f8cc8f535f68.jpeg)

Hey there. My laptop crashes every time I run the codes for mapping, as shown by the screenshot... However, I've tried this code before for other projects and it worked then so this shouldn't be happening? Not sure what's the issue here. Anyone got the same problem?

**Comment by abessudnov** [comment]
The last problem is computationally intensive, but it shouldn't crash your computer. Usually when there is a problem like this it means that there is something wrong with your code. Try to debug it, find what exactly causes the problem and try to change it.

**Comment by yo217** [comment]
Thanks! It was a silly mistake
