### ISSUE TITLE
markdown 

### ISSUE THREAD

**Issue by csddwfw** [dataanalysis3/datan3_2019#11]
Hi, 

Every time I  knit my markdown document it doesnt create a new MD file for me to commit to GitHub. I have never had this issue before. Where am I going wrong? 

Thanks in advance.

**Comment by csddwfw** [comment]
RMD works fine

**Comment by abessudnov** [comment]
I don't know what exactly is going wrong, but clearly something is and I'm sure you'll be able to fix it. :-)

**Comment by csddwfw** [comment]
I have managed to commit the MD to Git. However, it didn't give me an option to attach my graphs. When I click on the MD file from Github the graphs appear in the MD file - so I assume you should still be able to see them if I can?

**Comment by abessudnov** [comment]
Yes I can see your document and the graphs.

**Comment by csddwfw** [comment]
Thank-you.
