### ISSUE TITLE
Markdown not showing graphs

### ISSUE THREAD

**Issue by Omcgarry** [dataanalysis3/datan3_2019#12]
I can't seem to get my md file to show the graphs on github, yet it does show when I do the knit. 

I have submitted on Bart and committed it as well as the complete code on Github.

Thanks,
Ollie

**Comment by abessudnov** [comment]
Make sure you've committed on Github the files with your graphs.

**Comment by Omcgarry** [comment]
What do you mean? Do I need to save them all as individual images and then upload them? As I said, my knit shows all of the graphs (which I have uploaded), but when I open the Md on github it doesnt show.

**Comment by abessudnov** [comment]
I mean that you need to commit on Github the files for the graphs that you have already created when you knitted your document. The md file is a text file, it does not contain any images, only links to them.

**Comment by Omcgarry** [comment]
I understand. I tried to push the png files but it's been pushing for 30 minutes now and it still hasn't completed the operation.

I have emailed you the png files just in case it doesn't work before 2pm.

Thanks,
Ollie

**Comment by abessudnov** [comment]
I can't accept anything by email, but I hope you'll manage to push it successfully in the end.
