### ISSUE TITLE
Clarification on the output of the for loop (Last Q. for Assignment 5) 

### ISSUE THREAD

**Issue by hd371** [dataanalysis3/datan3_2019#15]
Am I expected to create a number of unique data frames creating unique 2by2 tables for each iteration of endogamic ethnic couples

OR 

am I expected to capture all of the endogamic ethnic couples in one df that is then looped? 

Many thanks,

**Comment by abessudnov** [comment]
Whatever works really, but my idea was that in each iteration you create an appropriate 2x2 data frame and calculate the odds ratio.

**Comment by hd371** [comment]
Okay, so what should be the specific rows and cols of the 2x2 data frames: 

e.g. White Non-White                                                                                                                                                                White  1          2                                                                                                                                                 Non-White 3   4                                                                                                                                                      

Or. (I'm assuming this...)

              White Chinese                                                                                                                                                       
White    1         2                                                                                                                                                     Chinese 3         4             (etc for all ethnicities) 

(+ column for the oddsratios or just print of the oddsratios) 

Many thanks,

**Comment by abessudnov** [comment]
You should calculate odds ratios for ethnic endogamy for each group, so your comparisons would be White British vs non-White British, Indian vs, non-Indian, etc.
