### ISSUE TITLE
Final Essay

### ISSUE THREAD

**Issue by csddwfw** [dataanalysis3/datan3_2019#16]
Dear Alexey, 

For the essay we are only allowed 5 graphs/tables. I have however tabulated a lot of my variables to check if they are coded correctly. Would you like us to print the output of these (i.e will they be counted as a table), or shall I set echo=FALSE? 

Thanks in advance.

**Comment by abessudnov** [comment]
You don't need to have these checks in the final version, so you can remove the code once everything has been finished, or comment it out.
