### ISSUE TITLE
Final Report Word Count (-/+ 10%)

### ISSUE THREAD

**Issue by hd371** [dataanalysis3/datan3_2019#18]
Can the word count for the Final Report be up to 2200 words, in accordance with the practices of the College of Social Sciences and International Studies? 

Many thanks,

**Comment by abessudnov** [comment]
Yes this is fine.

**Comment by hd371** [comment]
Thank you, also I am assuming we need to separately commit all graphs and tables separately to our private repositories alongside our RMD and pdf of our Final Report?

**Comment by abessudnov** [comment]
Yes. You'll need to check that they show correctly in your md file on Github and, of course, in your pdf documents that you'll submit on Bart.

**Comment by hd371** [comment]
Please can you clarify what you mean by: "You should conduct your analysis as a separate project on Github."  A separate project from what? 

I have all my code, analysis and interpretations in one md document (to submit to Github) and a pdf version in LaTeX to submit to eBart. 

Many thanks,

**Comment by abessudnov** [comment]
Yes, this is fine.
