### ISSUE TITLE
Graph and table limit query 

### ISSUE THREAD

**Issue by hd371** [dataanalysis3/datan3_2019#19]
I have 3 graphs, 1 table and 1 map in my report. 

I have also drawn manually using a flowchart software a Decision Tree for my classification of households. 

By linking you to the Decision Tree.pdf in the report does this count as going over the limit of 5 graphs and tables, and subsequently will I be marked down or can I include the decision tree drawing?

**Comment by abessudnov** [comment]
Yes you can include it.
