### ISSUE TITLE
Version Control

### ISSUE THREAD

**Issue by SM880** [dataanalysis3/datan3_2019#2]
I'd like to revert to a very early version of my repository, how do I go about doing this?

**Comment by abessudnov** [comment]
I don't think you can do this directly from the R Studio interface. You've got the following options.

1) Use Terminal (can be done from R Studio) and follow this: https://www.atlassian.com/git/tutorials/undoing-changes

2) Install and use Github Desktop: https://help.github.com/desktop-classic/guides/contributing/reverting-a-commit/

In both cases reverting a commit essentially means creating a new commit that will take you back to the previous state of your repo.

If you need to go to a very early version of your repo this may be too complicated and an easier solution would be to clone the original repo again and create a new project. Note that you can see the history of your commits in R Studio by clicking on the Git icon in the menu and then selecting History.
