### ISSUE TITLE
All codes being rewritten as NA

### ISSUE THREAD

**Issue by CatherineGalley** [dataanalysis3/datan3_2019#5]
When I run the code below, it seems to be rewriting everything as NA, rather than just variables coded as -9. This is the starter code and there's no dots so I don't think I need to change anything? 

Stable2 <- Stable2 %>%
        mutate(racel_dv = recode(racel_dv, `-9` = NA_real_))

**Comment by abessudnov** [comment]
This code should only change -9. check the minimal example:
library(tidyverse)
x <- data.frame(a = c(-9, 1, 2, 3))
x
mutate(x, y = recode(a, `-9` = NA_real_))

**Comment by abessudnov** [comment]
the last line is 
mutate(x, y = recode(a, \`-9\` = NA_real_))

**Comment by CatherineGalley** [comment]
The minimal example works great, but if I try it with the code from the assignment I get this error: Unreplaced values treated as NA as .x is not compatible. Please specify replacements exhaustively or supply .default

**Comment by abessudnov** [comment]
I just checked my solution, and it works fine. So there must be a mistake in your code somewhere. If you can't find it just modify the code so that it works as intended.
