### ISSUE TITLE
Knitting Assignment 3

### ISSUE THREAD

**Issue by Ali-Rey** [dataanalysis3/datan3_2019#7]
I've found that the .md file comes out extremely long as the base code in the "Reshape Data" section asks to print Long:

```

## Reshape data (20 points)

Now we have got the data from all 7 waves in the same data frame **all7** in the wide format. Note that the panel is unbalanced, i.e. we included all people who participated in at least one wave of the survey. Reshape the data to the long format. The resulting data frame should have six columns for six variables.

``{r}
Long <- all7 %>%
  ...
Long
``

```

I don't know if others are having this issue, but the output prints out 16666 rows of data. Is this intentional, or should I make it neater?

**Comment by yo217** [comment]
Hey yeah same here. I changed the code to print out just heads of the "Long" dataset so that it's neater. Otherwise it takes ages to knit as well!

**Comment by abessudnov** [comment]
It should be a tibble and the default print method should print just a few lines. If it causes problems do something like:
head(Long)
or
as_tibble(Long)

**Comment by Ali-Rey** [comment]
The head(Long) function works a lot better. Thank you!
